import { defineConfig, globalIgnores } from 'eslint/config'
import skipFormatting from 'eslint-config-prettier/flat'
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript'
import pluginBoundaries from 'eslint-plugin-boundaries'
import pluginImportX from 'eslint-plugin-import-x'
import pluginOxlint from 'eslint-plugin-oxlint'
import tseslint from 'typescript-eslint'

// Flat-config native stack (no eslint-config-next / FlatCompat bridge — that combo is flaky
// under eslint 9 + pnpm's strict node_modules and broke per-file lint-staged runs).
// TypeScript rules come from typescript-eslint; Next-specific rules (e.g. next/image hints)
// are intentionally dropped in favour of a lint pipeline that runs the same everywhere.

// Feature-Sliced Design layers, highest to lowest. A layer may only import from layers
// strictly below it (enforced by eslint-plugin-boundaries). Next `app/` routing dir is thin;
// FSD layers live under `src/`. The FSD "pages" layer is named `pageViews` because Next.js
// reserves `src/pages` for the Pages Router and would otherwise treat those slices as routes.
const FSD_LAYERS = ['app', 'pageViews', 'widgets', 'features', 'entities', 'shared'] as const

export default defineConfig(
  globalIgnores([
    '**/.next/**',
    '**/out/**',
    '**/coverage/**',
    '**/storybook-static/**',
    '**/playwright-report/**',
    '**/test-results/**',
    'next-env.d.ts', // generated by Next.js — do not edit/lint
    'src/shared/api/schema.d.ts', // generated by the gen-api-types skill
  ]),

  // TypeScript recommended (flat, non-type-checked — fast and CI-friendly).
  ...tseslint.configs.recommended,

  // ---- Import hygiene (eslint-plugin-import-x) ----
  {
    name: 'app/import-x',
    plugins: { 'import-x': pluginImportX },
    settings: {
      'import-x/resolver-next': [createTypeScriptImportResolver({ alwaysTryTypes: true })],
    },
    rules: {
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'type'],
          pathGroups: [{ pattern: '@/**', group: 'internal' }],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import-x/no-duplicates': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-cycle': ['error', { maxDepth: 3 }],
      'import-x/first': 'error',
      'import-x/newline-after-import': 'error',
    },
  },

  // ---- FSD layer boundaries (eslint-plugin-boundaries) ----
  {
    name: 'app/fsd-boundaries',
    files: ['src/**/*.{ts,tsx}'],
    plugins: { boundaries: pluginBoundaries },
    settings: {
      'boundaries/include': ['src/**/*'],
      'boundaries/elements': FSD_LAYERS.map((type) => ({
        type,
        pattern: `src/${type}/**`,
      })),
      'import/resolver': { typescript: true },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          rules: FSD_LAYERS.map((from, i) => ({
            from: { type: from },
            allow: { to: { type: FSD_LAYERS.slice(i) } },
          })),
        },
      ],
    },
  },

  // Test & story files: relax rules that don't apply to them.
  {
    name: 'app/test-overrides',
    files: ['**/*.spec.{ts,tsx}', '**/*.stories.{ts,tsx}', 'e2e/**/*.{ts,tsx}'],
    rules: {
      'boundaries/dependencies': 'off',
    },
  },

  ...pluginOxlint.buildFromOxlintConfigFile('.oxlintrc.json'),

  skipFormatting,
)
