/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects/{shareToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a project (with pins, rounds, computed remaining) by its share token. */
        get: operations["getProjectByShareToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{shareToken}/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a draft pin to the project. */
        post: operations["addPin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{shareToken}/pins/{pinId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
                pinId: components["parameters"]["PinId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a draft pin (only while draft). */
        delete: operations["deleteDraftPin"];
        options?: never;
        head?: never;
        /** Edit a draft pin (only while draft). */
        patch: operations["updateDraftPin"];
        trace?: never;
    };
    "/projects/{shareToken}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the current draft pins as a new round. */
        post: operations["submitRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
            code?: string;
        };
        /** @enum {string} */
        PinStatus: "draft" | "submitted" | "resolved";
        Pin: {
            /** Format: uuid */
            id: string;
            x: number;
            y: number;
            comment: string;
            authorName?: string | null;
            status: components["schemas"]["PinStatus"];
            roundNo: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        PinCreate: {
            x: number;
            y: number;
            comment: string;
            authorName?: string | null;
        };
        PinUpdate: {
            x?: number;
            y?: number;
            comment?: string;
        };
        Round: {
            no: number;
            /** Format: date-time */
            submittedAt: string;
            pinIds: string[];
        };
        Project: {
            /** Format: uuid */
            id: string;
            title: string;
            draftImageUrl: string | null;
            shareToken: string;
            includedRounds: number;
            usedRounds: number;
            remaining: number;
            overflow: number;
            pins: components["schemas"]["Pin"][];
            rounds: components["schemas"]["Round"][];
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Invalid input. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown share token or pin. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation not allowed in the current state (e.g. no remaining rounds, pin not draft). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ShareToken: string;
        PinId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProjectByShareToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    addPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinCreate"];
            };
        };
        responses: {
            /** @description The created draft pin. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pin"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDraftPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
                pinId: components["parameters"]["PinId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateDraftPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
                pinId: components["parameters"]["PinId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinUpdate"];
            };
        };
        responses: {
            /** @description The updated pin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pin"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    submitRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shareToken: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The created round. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
